// Code generated by Go Gateway. DO NOT EDIT.

package hello

import (
	entity "github.com/theluckiestsoul/protoc-gen-gogateway/example/pkg/proto/entity"
)

import (
	contract "github.com/theluckiestsoul/protoc-gen-gogateway/example/internal/repository/contract/hello"
	faker "github.com/go-faker/faker/v4"
	"context"
)

type helloserviceRepository struct {
}

func (s *helloserviceRepository) SayHello(ctx context.Context, req *entity.HelloRequest) (*entity.HelloResponse, error) {
	res := &entity.HelloResponse{}
	_ = faker.FakeData(res)
	return res, nil
}
func (s *helloserviceRepository) SayHelloAgain(ctx context.Context, req *entity.HelloRequest) (*entity.HelloResponse, error) {
	res := &entity.HelloResponse{}
	_ = faker.FakeData(res)
	return res, nil
}
func NewHelloServiceRepository() contract.HelloServiceRepository {
	return &helloserviceRepository{}
}
