// Code generated by Go Gateway. DO NOT EDIT.

package main

import (
	server "github.com/theluckiestsoul/protoc-gen-gogateway/example/internal/adapter/server"
)

func main() {
	server.RunServer(":9090")
}
